apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    proxy: guests
    route: healthcheck
  name: guests-healthcheck-rt
  namespace: gloo-system
spec:
  routes:
    - matchers:
        - headers:
            - name: ':method'
              value: GET
              invertMatch: true
          exact: /guests/healthcheck
      options:
        headerManipulation:
          responseHeadersToRemove:
            - content-type
          responseHeadersToAdd:
            - header:
                key: content-type
                value: application/json
      directResponseAction:
        body: '{"error_cd":"405","error_msg":"Invalid HTTP verb for the requested resource"}'
        status: 405
    - matchers:
        - exact: /guests/healthcheck
          methods:
            - GET
      options:
        prefixRewrite: /api/postgresql/health
        rateLimitConfigs:
          refs:
            - name: guests-health-rl
              namespace: gloo-system
        timeout: 5s
      routeAction:
        single:
          upstream:
            name: guests-us
            namespace: gloo-system