apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: basic-auth
  namespace: gloo-system
spec:
  configs:
    - basicAuth:
        apr:
          users:
            admin:
              salt: "gu6xai3m"
              hashedPassword: "zzdu/4VCSh4onyoUZKqZU1"