apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    proxy: guests
    route: healthcheck
  name: guests-rt
  namespace: gloo-system
spec:
  routes:
    - matchers:
      - headers:
        - name: ':method'
          value: GET
          invertMatch: true
        - name: ':method'
          value: PUT
          invertMatch: true
        - name: ':method'
          value: POST
          invertMatch: true
        exact: /guests
      options:
        headerManipulation:
          responseHeadersToRemove:
            - content-type
          responseHeadersToAdd:
            - header:
                key: content-type
                value: application/json
      directResponseAction:
        body: '{"error_cd":"405","error_msg":"Invalid HTTP verb for the requested resource"}'
        status: 405
    - matchers:
      - exact: /guests
        methods:
          - GET
          - PUT
          - POST
      options:
        prefixRewrite: /api/postgresql/guests
        rateLimitConfigs:
          refs:
            - name: guests-rl
              namespace: gloo-system
        timeout: 5s
      routeAction:
        single:
          upstream:
            name: guests-us
            namespace: gloo-system