apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  labels:
    proxy: admin
  name: admin-restart-rl
  namespace: gloo-system
spec:
  raw:
    descriptors:
      - key: generic_key
        value: count
        rateLimit:
          requestsPerUnit: 1
          unit: MINUTE
    rateLimits:
      - actions:
          - genericKey:
              descriptorValue: count