apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    proxy: guests
    route: healthcheck
  name: admin-init-rt
  namespace: gloo-system
spec:
  routes:
    - matchers:
        - headers:
            - name: ':method'
              value: POST
              invertMatch: true
          exact: /admin/init
      options:
        headerManipulation:
          responseHeadersToRemove:
            - content-type
          responseHeadersToAdd:
            - header:
                key: content-type
                value: application/json
      directResponseAction:
        body: '{"error_cd":"405","error_msg":"Invalid HTTP verb for the requested resource"}'
        status: 405
    - matchers:
        - methods:
            - POST
          headers:
            - name: Authorization
              invertMatch: true
          exact: /admin/init
      options:
        headerManipulation:
          responseHeadersToRemove:
            - content-type
          responseHeadersToAdd:
            - header:
                key: content-type
                value: application/json
      directResponseAction:
        body: '{"error_cd":"401","error_msg":"Missing Authorization Header"}'
        status: 401
    - matchers:
        - methods:
            - POST
          headers:
            - name: Authorization
              value: "Basic YWRtaW46cGFzc3dvcmQ="
              invertMatch: true
          exact: /admin/init
      options:
        headerManipulation:
          responseHeadersToRemove:
            - content-type
          responseHeadersToAdd:
            - header:
                key: content-type
                value: application/json
      directResponseAction:
        body: '{"error_cd":"401","error_msg":"Invalid username or password"}'
        status: 401
    - matchers:
        - exact: /admin/init
          methods:
            - POST
          headers:
            - name: Authorization
              value: "Basic YWRtaW46cGFzc3dvcmQ="
      options:
        extauth:
          configRef:
            name: basic-auth
            namespace: gloo-system
        prefixRewrite: /api/postgresql/init
        rateLimitConfigs:
          refs:
            - name: admin-init-rl
              namespace: gloo-system
        timeout: 5s
      routeAction:
        single:
          upstream:
            name: admin-us
            namespace: gloo-system