apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    proxy: guests
    route: parent
  name: admin-prt
  namespace: gloo-system
spec:
  routes:
    - matchers:
        - prefix: /admin/restart
      delegateAction:
        name: admin-restart-rt
        namespace: gloo-system
    - matchers:
        - prefix: /admin/init
      delegateAction:
        name: admin-init-rt
        namespace: gloo-system