apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  type: NodePort
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30096
      name: first
    - port: 8920
      targetPort: 8920
      nodePort: 30920
      name: second
  selector:
    app: jellyfin
